### ISSUE TITLE
Make a functional landing page skeleton

### ISSUE THREAD

**Issue by poornaraob** [EnCiv/undebate#196]
- [x] Make a functional wireframe to arrange the components of layout. 
> Discussion points (05/27/2020):Dana/David
- > Pair programming will be a good approach. One person creates a draft with minor adjustment and develop. 
- > Propose to develop in isolation and later integrate. All development will be on react. 
- > Goes into web component directory
- > "readme" outlines the necessary details for creating a new page
- >  During development, keep in mind both portrait and landscape mode view 

- [x] Create a first pass conversion of adobe design to react

Link for the adobe UI design: https://xd.adobe.com/view/2b23caec-3565-476c-7d1e-17fcb81575b7-5d12/screen/c01bb3fc-bf9b-4412-9bdb-aa83c38a1ff3/Landing-Page-V3-2

**Comment by poornaraob** [comment]
06/10: 
- Hartford agreed to blue/white design. Decision made based on the poll.
- The selector and text is left aligned. Different from Tracy's design. 
- Review the design / API with @tianchili11 , @MrNanosh and @ddfridley on 06/15 1.00pm (google meet up link).

**Comment by ddfridley** [comment]
Here is the link for the combined logo: https://res.cloudinary.com/hf6mryjpf/image/upload/v1591846510/assets/EnCivCandidateConversations.svg

**Comment by ddfridley** [comment]
Review with @MrNanosh and @tianchili11 
landscape mode
- [ ]  Hartford Votes ~ Vota Coalition should be horizontally centered above hero image
- [ ]  Logos on left and right are taller than the banner area
- [ ] Logo's vertical alignment are different - we need to remove the white space [ ] Click here to ask questions comes off the image on long viewports
- [ ] Space above "candidate conversations" sections should be same as below
- [ ] When the viewport is very wide, the image behind Candidate Conversations doesn't get wide enought.
portait mode
- [ ] Space above "click her to ask question" should be like the space above candidate conversations and the space below
- [ ] Hartord logo and enciv-candidtes logo should be vertically centered in the banner area (like the hamberger) 
- [ ] Hamburger menu style update, renter hamburger menu on right. 
- [ ] Swap Hamburger buton and logos left-right.
- [ ] David to send links for buttons, etc.
  
Instead of hello world add an iframe for https://cc.enciv.org/san-francisco-district-attorney

**Comment by poornaraob** [comment]
06/17: Implemented the skeleton landing page.
