### ISSUE TITLE
Investigate on District API 

### ISSUE THREAD

**Issue by poornaraob** [EnCiv/undebate#202]
District API needs to fetch the address information and direct respective district for voters. Need to investigate on who will provide this information and how it will be incorporated

**Comment by poornaraob** [comment]
06/10: 
We can't use google civic info API as they don't have state legislation info. 
Working with Ballotpedia to check if we can use their API.

**Comment by poornaraob** [comment]
06/17: 
In communication with Ballotpedia. Planning to meet on 06/18 with Ballotpedia - David 
Other option is to look at google civic API.

**Comment by MrNanosh** [comment]
google maps is being used to return lat and long data from Google maps geocoder API using addresses. This lat and long data is then being used to find offices that are filtered for offices of interest. 

currently in testing and refinement:
- [ ] retrieving a list of viewers URLs from the database
- [ ] error handling in the event of missing environment variables
- [ ] error handling for google maps API error 
- [ ] error handling for ELECTED_OFFICIALS_URL

additional needs
- [ ] hartford-address-lookup needs to prevent the use of google maps for addresses that lack Hartford, CT 
- [ ] if zip-code is provided check zipcode prior to using google maps API in a hash that contains all Hartford zipcodes
- [ ] address must be in a street_num street_name, city, state zip format otherwise return a message to users
- [ ] UI/UX needed for validation messages

**Comment by poornaraob** [comment]
07:24:Work in Progress. 

Update from Dana:
Testing and validation is in progress. Create a new ticket for UI/UX design requirement

**Comment by poornaraob** [comment]
07/01: 
Work in progress. 
Dana @MrNanosh will lead discussion with @tianchili11 and Andelino for next step on UI/UX design requirement in this week and create a new task for UI/UX requirement.

**Comment by MrNanosh** [comment]
UI is in testing phase

**Comment by poornaraob** [comment]
07/08: Is done for now.
