### ISSUE TITLE
Unit test environment setup

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#58]
I had to do a unit test.  I put it in app/tests.  It's just a stand alone file that runs and exits, returning the number of errors.  I know there are better environments for this - but we need to set it up and document how to.   

So the issue is to decide on a unit test environment, set it up, and convert the one unit test into that format.    

Consider that we should do a lot of unit tests of react components. 

Sometimes we have to test how the react component interacts with the browser - like react-camera-recorder.  This may require something like storybook and that a human actually exectute these steps, but we need to layout the steps.  So it may be separate from automated unit tests - but we have to have a plan.

**Comment by djbowers** [comment]
So I have been doing some research into the different testing frameworks that are out there, and it seems like the two mains ones for testing React apps are Jest and Mocha. 

After going through some tutorials for each, I can safely say that they both would work fine for us. There is some more setup required to get Mocha working, as well as a few additional libraries that are required such as Chai and Sinon in order to get assertions and mocks/stubs/spies that Jest comes with by default.

Also Jest comes with snapshot functionality baked in, which could be a great way to test individual React components. 

I would say in general, unless we have a specific reason to need the additional customization that is required by Mocha, we would be safe to stick with Jest.

**Comment by pewkers** [comment]
I have used JEST. It works well, it's well documented, and it is easy to use. The only downside that I can think of is it gets a bit tedious in certain parts.

**Comment by ddfridley** [comment]
Ok - so Jest it is. I like it because there is support for using it with Storybook - https://storybook.js.org/docs/testing/automated-visual-testing/ 

I can see that we are going to have to end up with a range of test environments, low lever unit tests for .js code, visual tests (woes it look right when its rendered), interactive tests (if video data stalls, does the stall window pop up and show something), and end to end tests (cypress).

**Comment by ddfridley** [comment]
@djbowers I looked through the code and couldn't find another example of something JS that didn't interact with anything else.  We either have to build tests of things that use the db, or test things that render.  app/components/preamble.jsx seems to be about the simplest thing that renders.   

In this repo: https://github.com/EnCiv/iota I have taken the Iota model and made a separate repo out of it, so it can be included in multiple projects.  In this repo there is test.js that starts up a local mongo db, and then tests it.  You could jestify this repo, and I could migrate toward using it in undebate. But also, this could be the basis for how to create tests of things that use the mongodb, like the APIs in app/apis.
