### ISSUE TITLE
Tests run twice

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate#83]
Great to have the jest test environment setup!
I notice that when I run it the tests run twice:
```
$ npm run test

> undebate@0.0.0 test C:\Users\dfri\git\enciv\undebate
> jest --config ./jest.config.json

 PASS  app/components/lib/__tests__/cloudinary-urls.test.js (6.689s)
 PASS  dist/components/lib/__tests__/cloudinary-urls.test.js (6.672s)

Test Suites: 2 passed, 2 total
Tests:       6 passed, 6 total
Snapshots:   0 total
Time:        9.01s
```
The dist directory is created when you `npm run postinstall` or `npm run dev` and that's where all the babel converted .jsx -> .js files end up. 

Under the app/ tree  For .jsx files and even some .js files that need polyfills they won't run. 

We need to config jest to run in only the dist/... tree.

**Comment by djbowers** [comment]
@ddfridley good point. But wouldn't we want to run the tests in `app/` and then not actually include the tests in `dist/` in the first place? I would think tests shouldn't be included in production, right?

I'm actually curious why we don't bundle all of the javascript files together with webpack in production? In webpack-prod.config.js, we have
```
  output: {
    path: path.join(__dirname, 'assets/webpack'),
    filename: '[name].js',
  },
```
Couldn't we just bundle all the js files together? Is there a reason they are kept separate? Maybe something like this?
```
  output: {
    path: __dirname + '/dist',
    publicPath: '/',
    filename: 'bundle.js'
  },
```
Maybe there is a reason we need the js files kept separate?

**Comment by ddfridley** [comment]
The reason to bundle main.js for the browser is optimize the download time - one big file is faster to download than lots of small files.  On the server side, all the files are already there so there is no speed up from bundling them - and I worry that if bundled we will lose context of where exceptions get thrown from.  I've not heard of bundling on the server side - if there are things I'm not seeing I'd like to learn about it.

If you run tests in the app tree, some won't work unless we add have some other mechanism for running babel on the files before we run the tests.   (for example, import is still experimental in node and so babel needs to convert imports to requires).

But maybe I'm we needs to discuss  with a whiteboard or something.  The code for the tests should be in app tree as it is now.   But the tests should run on the files in dist.   The dist tree is not included in the repo, and whenever you install the repo (or push to heroku), the dist tree is built from scratch. 

Lets talk about this - I want to make sure I'm not missing something.

**Comment by djbowers** [comment]
So I think that PR should close this issue. After doing some reading, it's my general feeling that most unit tests should still test against the `src/` dir (or `app/` in our case), but that integration and e2e tests should be run against the `dist/` dir.

The main reason I think it should be this way is because we agreed that the unit tests should be located as close as possible to the code they are testing. Placing them in the `app/` dir but then importing the code we are testing from the `dist/` dir would be confusing imo. 

However, integration and e2e tests can be kept in separate directories specifically for tests, and they can import the code under test from `dist/` at that point. Then it is required to build the project to run integration/e2e tests, but devs can keep their unit tests running quickly and automatically against the `app/` dir. 

Also as mentioned in the PR, Jest has a plugin called `babel-jest` that is used to transpile your Node backend code with babel before running the tests against it, so I think that covers all of our unit testing bases.

**Comment by ddfridley** [comment]
Your last paragraph, about babel-jest really answered my concern.  I didn't know jest would run babel on the code in app/ before testing it.  With that, it makes perfect sense to exclude __test__ from the dist tree.

**Comment by poornaraob** [comment]
Update from Standup 03/16: 
Write up set of E2E test cases to run in cyress (Action item: @ddfridley )
